"""
context_menu/formats.py
No Qt dependency
"""

CONVERSION_MAP: dict = {
    # Images
    "jpg":  ["image_to_pdf", "image_to_png", "image_to_jpeg", "image_to_webp",
             "image_to_bmp", "image_to_tiff", "image_to_avif", "image_to_j2k",
             "image_to_svg", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_jpg", "images_to_pdf_merged"],
    "jpeg": ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_webp",
             "image_to_bmp", "image_to_tiff", "image_to_avif", "image_to_j2k",
             "image_to_svg", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_jpeg", "images_to_pdf_merged"],
    "png":  ["image_to_pdf", "image_to_jpg", "image_to_jpeg", "image_to_webp",
             "image_to_bmp", "image_to_tiff", "image_to_avif", "image_to_j2k",
             "image_to_svg", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_png", "images_to_pdf_merged"],
    "webp": ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_bmp", "image_to_tiff", "image_to_avif", "image_to_j2k",
             "image_to_svg", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_webp", "images_to_pdf_merged"],
    "bmp":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_tiff", "image_to_avif", "image_to_j2k",
             "image_to_svg", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_bmp", "images_to_pdf_merged"],
    "tiff": ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_avif", "image_to_j2k",
             "image_to_svg", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_tiff", "images_to_pdf_merged"],
    "tif":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_avif", "image_to_j2k",
             "image_to_svg", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_tif", "images_to_pdf_merged"],
    "heic": ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_psd",
             "image_to_dng", "image_to_heic", "images_to_pdf_merged"],
    "jfif": ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_psd",
             "image_to_dng", "image_to_heic", "images_to_pdf_merged"],
    "heif": ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_psd",
             "image_to_dng", "image_to_heic", "images_to_pdf_merged"],
    "avif": ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_j2k",
             "image_to_svg", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_avif", "images_to_pdf_merged"],
    "gif":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_heic",
             "image_to_psd", "image_to_dng", "images_to_pdf_merged"],
    "psd":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_heic",
             "image_to_dng", "image_to_psd", "images_to_pdf_merged"],
    "svg":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_svg", "images_to_pdf_merged"],
    "j2k":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_svg", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_j2k", "images_to_pdf_merged"],
    "jp2":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_svg", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_j2k", "images_to_pdf_merged"],
    "jpx":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_svg", "image_to_ico", "image_to_heic", "image_to_psd",
             "image_to_dng", "image_to_j2k", "images_to_pdf_merged"],
    "dng":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_heic",
             "image_to_psd", "image_to_dng", "images_to_pdf_merged"],
    "raw":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_heic",
             "image_to_psd", "image_to_dng", "images_to_pdf_merged"],
    "cr2":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_heic",
             "image_to_psd", "image_to_dng", "images_to_pdf_merged"],
    "cr3":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_heic",
             "image_to_psd", "image_to_dng", "images_to_pdf_merged"],
    "nef":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_heic",
             "image_to_psd", "image_to_dng", "images_to_pdf_merged"],
    "arw":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_heic",
             "image_to_psd", "image_to_dng", "images_to_pdf_merged"],
    "orf":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_heic",
             "image_to_psd", "image_to_dng", "images_to_pdf_merged"],
    "rw2":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_heic",
             "image_to_psd", "image_to_dng", "images_to_pdf_merged"],
    "raf":  ["image_to_pdf", "image_to_png", "image_to_jpg", "image_to_jpeg",
             "image_to_webp", "image_to_bmp", "image_to_tiff", "image_to_avif",
             "image_to_j2k", "image_to_svg", "image_to_ico", "image_to_heic",
             "image_to_psd", "image_to_dng", "images_to_pdf_merged"],
    # Documents
    "docx": [
        "docx_to_pdf",
        "merge_docx_none", "merge_docx_alpha_asc", "merge_docx_alpha_desc",
        "merge_docx_num_asc", "merge_docx_num_desc",
        "merge_docx_date_asc", "merge_docx_date_desc",
    ],
    "doc":  [
        "docx_to_pdf",
        "merge_docx_none", "merge_docx_alpha_asc", "merge_docx_alpha_desc",
        "merge_docx_num_asc", "merge_docx_num_desc",
        "merge_docx_date_asc", "merge_docx_date_desc",
    ],
    "pdf":  [
        "pdf_to_docx", "pdf_to_html",
        "merge_pdf_none", "merge_pdf_alpha_asc", "merge_pdf_alpha_desc",
        "merge_pdf_num_asc", "merge_pdf_num_desc",
        "merge_pdf_date_asc", "merge_pdf_date_desc",
    ],
    "txt":  ["txt_to_pdf",  "txt_to_docx"],
    "rtf":  ["rtf_to_pdf",  "rtf_to_docx"],
    "xlsx": ["xlsx_to_pdf", "xlsx_to_csv",  "xlsx_to_json"],
    "pptx": ["pptx_to_pdf"],
    "html": ["html_to_pdf"],
    "epub": ["epub_to_pdf"],
    "csv":  ["csv_to_json"],
    "json": ["json_to_csv"],
    # Audio
    "wav":  ["audio_to_mp3", "audio_to_aac", "audio_to_flac", "audio_to_ogg",  "audio_to_m4a", "audio_to_wav"],
    "mp3":  ["audio_to_wav", "audio_to_aac", "audio_to_flac", "audio_to_ogg",  "audio_to_m4a", "audio_to_mp3"],
    "aac":  ["audio_to_mp3", "audio_to_wav", "audio_to_flac", "audio_to_ogg",  "audio_to_m4a", "audio_to_aac"],
    "flac": ["audio_to_mp3", "audio_to_wav", "audio_to_aac",  "audio_to_ogg",  "audio_to_m4a", "audio_to_flac"],
    "ogg":  ["audio_to_mp3", "audio_to_wav", "audio_to_aac",  "audio_to_flac", "audio_to_m4a", "audio_to_ogg"],
    "m4a":  ["audio_to_mp3", "audio_to_wav", "audio_to_aac",  "audio_to_flac", "audio_to_ogg", "audio_to_m4a"],
    # Video
    "avi":  ["video_to_mp4", "video_to_mkv", "video_to_webm", "video_to_mov", "video_to_avi",
             "video_to_mp3", "video_to_wav", "video_to_aac",  "video_to_flac"],
    "webm": ["video_to_mp4", "video_to_mkv", "video_to_avi",  "video_to_mov", "video_to_webm",
             "video_to_mp3", "video_to_wav", "video_to_aac",  "video_to_flac"],
    "mkv":  ["video_to_mp4", "video_to_avi", "video_to_webm", "video_to_mov", "video_to_mkv",
             "video_to_mp3", "video_to_wav", "video_to_aac",  "video_to_flac"],
    "mov":  ["video_to_mp4", "video_to_mkv", "video_to_avi",  "video_to_webm", "video_to_mov",
             "video_to_mp3", "video_to_wav", "video_to_aac",  "video_to_flac"],
    "mp4":  ["video_to_mkv", "video_to_avi", "video_to_webm", "video_to_mov", "video_to_mp4",
             "video_to_mp3", "video_to_wav", "video_to_aac",  "video_to_flac"],
}

# Maps conversion_type → (merge_func, order_key)
MERGE_DISPATCH: dict = {
    "merge_pdf_none":       ("pdf",  "none"),
    "merge_pdf_alpha_asc":  ("pdf",  "alphabetical_asc"),
    "merge_pdf_alpha_desc": ("pdf",  "alphabetical_desc"),
    "merge_pdf_num_asc":    ("pdf",  "numerical_asc"),
    "merge_pdf_num_desc":   ("pdf",  "numerical_desc"),
    "merge_pdf_date_asc":   ("pdf",  "date_asc"),
    "merge_pdf_date_desc":  ("pdf",  "date_desc"),
    "merge_docx_none":       ("docx", "none"),
    "merge_docx_alpha_asc":  ("docx", "alphabetical_asc"),
    "merge_docx_alpha_desc": ("docx", "alphabetical_desc"),
    "merge_docx_num_asc":    ("docx", "numerical_asc"),
    "merge_docx_num_desc":   ("docx", "numerical_desc"),
    "merge_docx_date_asc":   ("docx", "date_asc"),
    "merge_docx_date_desc":  ("docx", "date_desc"),
}

LABELS: dict = {
    "image_to_pdf":         "Image → PDF",
    "image_to_png":         "Image → PNG",    "image_to_jpg":   "Image → JPG",
    "image_to_jpeg":        "Image → JPEG",   "image_to_bmp":   "Image → BMP",
    "image_to_webp":        "Image → WEBP",   "image_to_tiff":  "Image → TIFF",
    "image_to_heic":        "Image → HEIC",   "image_to_avif":  "Image → AVIF",
    "image_to_psd":         "Image → PSD",    "image_to_svg":   "Image → SVG",
    "image_to_dng":         "Image → DNG",    "image_to_ico":   "Image → ICO",
    "image_to_j2k":         "Image → J2K",
    "images_to_pdf_merged": "Images → PDF (merged)",
    "docx_to_pdf":          "Word → PDF",     "pdf_to_docx":    "PDF → Word",
    "txt_to_pdf":           "TXT → PDF",      "txt_to_docx":    "TXT → DOCX",
    "rtf_to_pdf":           "RTF → PDF",      "rtf_to_docx":    "RTF → DOCX",
    "xlsx_to_pdf":          "XLSX → PDF",     "xlsx_to_csv":    "XLSX → CSV",
    "xlsx_to_json":         "XLSX → JSON",    "pptx_to_pdf":    "PPTX → PDF",
    "html_to_pdf":          "HTML → PDF",     "pdf_to_html":    "PDF → HTML",
    "epub_to_pdf":          "EPUB → PDF",     "csv_to_json":    "CSV → JSON",
    "json_to_csv":          "JSON → CSV",
    # Merge PDF
    "merge_pdf_none":       "Merge PDFs (current order)",
    "merge_pdf_alpha_asc":  "Merge PDFs (name A → Z)",
    "merge_pdf_alpha_desc": "Merge PDFs (name Z → A)",
    "merge_pdf_num_asc":    "Merge PDFs (number ↑)",
    "merge_pdf_num_desc":   "Merge PDFs (number ↓)",
    "merge_pdf_date_asc":   "Merge PDFs (date oldest first)",
    "merge_pdf_date_desc":  "Merge PDFs (date newest first)",
    # Merge DOCX
    "merge_docx_none":       "Merge Word docs (current order)",
    "merge_docx_alpha_asc":  "Merge Word docs (name A → Z)",
    "merge_docx_alpha_desc": "Merge Word docs (name Z → A)",
    "merge_docx_num_asc":    "Merge Word docs (number ↑)",
    "merge_docx_num_desc":   "Merge Word docs (number ↓)",
    "merge_docx_date_asc":   "Merge Word docs (date oldest first)",
    "merge_docx_date_desc":  "Merge Word docs (date newest first)",
    # Audio
    "audio_to_mp3":  "Audio → MP3",   "audio_to_wav":  "Audio → WAV",
    "audio_to_aac":  "Audio → AAC",   "audio_to_ogg":  "Audio → OGG",
    "audio_to_flac": "Audio → FLAC",  "audio_to_m4a":  "Audio → M4A",
    # Video
    "video_to_mp4":  "Video → MP4",   "video_to_mkv":  "Video → MKV",
    "video_to_avi":  "Video → AVI",   "video_to_webm": "Video → WEBM",
    "video_to_mov":  "Video → MOV",   "video_to_mp3":  "Video → MP3",
    "video_to_wav":  "Video → WAV",   "video_to_aac":  "Video → AAC",
    "video_to_flac": "Video → FLAC",
}