import { Agent } from "./types";

export const DEFAULT_AGENTS: Agent[] = [
  {
    id: "agent-gpt-gemini",
    name: "Gemini Agent",
    provider: "Google Gemini 3.5 Flash",
    role: "Conversational & Smart Brain",
    bestFor: "Normal conversations, task structuring, decision planning, and general reasoning",
    status: "online",
    speed: "Ultra Fast",
    costLevel: "Free",
    icon: "BrainCircuit",
    description: "The primary direct Google Gemini API conversational channel. Best for general help and direct guidance."
  },
  {
    id: "agent-gpt",
    name: "GPT Agent",
    provider: "OpenAI GPT-4o",
    role: "General Specialist & Developer",
    bestFor: "Refactoring code, standard formatting, business models drafting, and translation",
    status: "online",
    speed: "Ultra Fast",
    costLevel: "Medium",
    icon: "BrainCircuit",
    description: "State-of-the-art general reasoning model tuned for structured specifications and high fidelity drafts."
  },
  {
    id: "agent-claude",
    name: "Claude Agent",
    provider: "Anthropic / Gemini Reasoning",
    role: "Long Reasoning & Structural Expert",
    bestFor: "Clean designs, complex mathematical models, multi-turn reasoning, and system specifications",
    status: "online",
    speed: "High Reasoning",
    costLevel: "High",
    icon: "Compass",
    description: "Optimized for system integrity, deep logic flows, and architectural blueprints."
  },
  {
    id: "agent-deepseek",
    name: "DeepSeek Agent",
    provider: "DeepSeek / Gemini Architect",
    role: "Coding Specialist",
    bestFor: "Complex software architecture, full-stack components, algorithm debugging, and DB setup",
    status: "online",
    speed: "Fast",
    costLevel: "Low",
    icon: "CodeXml",
    description: "Pre-loaded with deep semantic models tuned for precision coding, compiling, and testing."
  },
  {
    id: "agent-kimi",
    name: "Kimi Agent",
    provider: "Kimi / Gemini Long-Context",
    role: "Document & Large Corpus Digest",
    bestFor: "Long documents, multiple legal drafts, large PDFs, and raw code bases",
    status: "online",
    speed: "Balanced",
    costLevel: "Medium",
    icon: "FileSearch",
    description: "Accepts up to 2 million tokens of user data to retrieve structures seamlessly."
  },
  {
    id: "agent-grok",
    name: "Grok Agent",
    provider: "SERP + Google Grounded Gemini",
    role: "Real-Time Internet Analyst",
    bestFor: "Latest events, trends, live prices, news summaries, and ground truth searches",
    status: "online",
    speed: "Balanced",
    costLevel: "Medium",
    icon: "Globe",
    description: "Injects Google Search grounding live engine to secure real-time citations."
  },
  {
    id: "agent-qwen",
    name: "Qwen Agent",
    provider: "Alibaba Qwen Core",
    role: "Multilingual Reasoning",
    bestFor: "Language localization, parsing eastern character sets, custom tokenizing, high precision analysis",
    status: "online",
    speed: "Fast",
    costLevel: "Low",
    icon: "Bot",
    description: "Top-tier multilingual model designed for translation accuracy and complex structured queries."
  },
  {
    id: "agent-llama",
    name: "Llama Agent",
    provider: "Meta LLaMA 3.1",
    role: "Open Source Advocate",
    bestFor: "Highly custom workflows, fast conversation, function calling, structured json responses",
    status: "online",
    speed: "Ultra Fast",
    costLevel: "Low",
    icon: "Bot",
    description: "Powerful, high-efficiency open weights LLM capable of swift technical responses."
  },
  {
    id: "agent-mistral",
    name: "Mistral Agent",
    provider: "Mistral AI MoE",
    role: "European LLM Core",
    bestFor: "Compact semantic reasoning, high token density, fast function executions",
    status: "online",
    speed: "Fast",
    costLevel: "Low",
    icon: "Bot",
    description: "Specialized Mixture of Experts engine known for strong reasoning in a compact token payload."
  },
  {
    id: "agent-glm",
    name: "GLM / Z.AI Agent",
    provider: "Zhipu AI GLM-4",
    role: "Bilingual Cognitive Expert",
    bestFor: "Advanced agentic actions, complex tool invocation, bilingual Chinese-English queries",
    status: "online",
    speed: "Fast",
    costLevel: "Low",
    icon: "Bot",
    description: "Advanced cognitive reasoning model supporting robust multi-turn task structures."
  },
  {
    id: "agent-openrouter",
    name: "OpenRouter Agent",
    provider: "OpenRouter Gateway",
    role: "Universal Model Aggregator",
    bestFor: "Accessing hundreds of models through a single developer API, redundancy management",
    status: "online",
    speed: "Balanced",
    costLevel: "Medium",
    icon: "Globe",
    description: "Unified interface routing requests to any available open or closed-source LLM."
  },
  {
    id: "agent-aiml",
    name: "AIML Agent",
    provider: "AIML API",
    role: "Developer API Multiplex",
    bestFor: "Consolidated API pipelines, rapid mock prototyping, developer-oriented testing",
    status: "online",
    speed: "Fast",
    costLevel: "Low",
    icon: "Cpu",
    description: "Highly robust developer-centric endpoints for text generation, translation, and summaries."
  },
  {
    id: "agent-smartchat",
    name: "Smart Chat Agent",
    provider: "Chitti-Robo Dynamic Router",
    role: "Meta Intelligent Router",
    bestFor: "Dynamically matching prompt topics with the absolute best agent cluster for peak quality",
    status: "online",
    speed: "Ultra Fast",
    costLevel: "Free",
    icon: "BrainCircuit",
    description: "Evaluates your message semantic tone and routes it to Claude, Gemini, or DeepSeek automatically."
  },
  {
    id: "agent-higgsfield",
    name: "Higgsfield Agent",
    provider: "Higgsfield / Imagen Format",
    role: "Art Direction & Cinematic Prompt Generator",
    bestFor: "Scenic video prompts, cinematic imagery cues, lighting codes, of anime/product compositions",
    status: "online",
    speed: "Fast",
    costLevel: "Low",
    icon: "FlameKindling",
    description: "Translates standard scripts into rich directors' cuts with precise camera tracks and lighting ratios."
  },
  {
    id: "agent-cloudconvert",
    name: "CloudConvert Agent",
    provider: "CloudConvert Pipeline",
    role: "Format conversion engine",
    bestFor: "PDF to Word templates, Text-to-DOCX, PDF compilation, image styling, media tuning",
    status: "online",
    speed: "Ultra Fast",
    costLevel: "Low",
    icon: "FileOutput",
    description: "Converts files on-the-fly and repackages data into fully readable structures."
  },
  {
    id: "agent-serp",
    name: "SERP Search Agent",
    provider: "Google SERP Grounding",
    role: "Web Crawler & Fact Checker",
    bestFor: "Extracting precise Google Search URLs, citations, real-time weather, or financial records",
    status: "online",
    speed: "Balanced",
    costLevel: "Low",
    icon: "Globe",
    description: "Directly executes search queries over Google Index and formats cited findings."
  },
  {
    id: "agent-noiz",
    name: "NOIZ Audio Agent",
    provider: "NOIZ Audio Core",
    role: "Acoustic System Designer",
    bestFor: "Designing soundscapes, planning podcast structures, voiceover alignments, sound syntheses",
    status: "online",
    speed: "Fast",
    costLevel: "Medium",
    icon: "FileOutput",
    description: "Acoustic intelligence system trained to structure custom audio loops and ambient scripts."
  },
  {
    id: "agent-memory",
    name: "Text Embedding Agent",
    provider: "Gemini Embedding Preview",
    role: "Long-Term Cognitive Memory Finder",
    bestFor: "Saving contextual preferences, searching historical chats, retrieving file schemas",
    status: "online",
    speed: "Ultra Fast",
    costLevel: "Free",
    icon: "DatabaseBackup",
    description: "Maintains a full cosine-similarity search stack to anchor context automatically."
  },
  {
    id: "agent-dalle",
    name: "DALL-E Image Agent",
    provider: "OpenAI DALL-E 3",
    role: "Visual Creative Designer",
    bestFor: "Generating high-resolution photorealistic images, stylized sketches, and brand icons",
    status: "online",
    speed: "Balanced",
    costLevel: "High",
    icon: "FlameKindling",
    description: "State-of-the-art text-to-image engine turning written prompts into beautiful visual assets."
  },
  {
    id: "agent-tts",
    name: "TTS Voice Agent",
    provider: "ElevenLabs / OpenAI TTS",
    role: "Speech Synthesis Engine",
    bestFor: "High-fidelity lifelike vocal reads, speech cadence matching, audiobook script narrations",
    status: "online",
    speed: "Ultra Fast",
    costLevel: "High",
    icon: "FileOutput",
    description: "Converts written text segments into extremely natural, human-sounding spoken audio streams."
  },
  {
    id: "agent-supabase",
    name: "Supabase Backend Agent",
    provider: "Supabase Postgres Admin",
    role: "Database Architect & Real-time Integrator",
    bestFor: "Postgres database structuring, Row Level Security (RLS) policies, authentication tables setup",
    status: "online",
    speed: "Ultra Fast",
    costLevel: "Free",
    icon: "DatabaseBackup",
    description: "Helper agent designed to structure table schemas and setup Supabase developer dashboards."
  },
  {
    id: "agent-neon",
    name: "Neon Database Agent",
    provider: "Neon Serverless SQL",
    role: "Serverless Database Designer",
    bestFor: "Branching Postgres environments, rapid data warehousing, query optimizations",
    status: "online",
    speed: "Ultra Fast",
    costLevel: "Free",
    icon: "DatabaseBackup",
    description: "Assists with configuring serverless PostgreSQL clusters and writing highly optimized queries."
  },
  {
    id: "agent-21stdev",
    name: "21st.dev UI Agent",
    provider: "21st.dev UI Registry",
    role: "Component Visual Synthesizer",
    bestFor: "Copy-pasteable Tailwind CSS widgets, modern React UI layouts, shadcn blueprints",
    status: "online",
    speed: "Fast",
    costLevel: "Free",
    icon: "CodeXml",
    description: "Discovers premium modern designs, widgets, and styles to implement beautiful components instantly."
  },
  {
    id: "agent-orcarouter",
    name: "OrcaRouter Agent",
    provider: "Orca Intelligent Router",
    role: "Arbitrage & Smart Cost Estimator",
    bestFor: "Calculating optimal model routing based on real-time token cost and model speeds",
    status: "online",
    speed: "Balanced",
    costLevel: "Free",
    icon: "Compass",
    description: "Reduces API expenses by evaluating query difficulty and selecting the most economical route."
  },
  {
    id: "agent-nvidia",
    name: "Nvidia Kimi Agent",
    provider: "NVIDIA AI Endpoints (kimi-k2.6)",
    role: "Deep Reasoning & Context Expert",
    bestFor: "Complex analytical queries, deep reasoning, and precise multi-turn chat alignment",
    status: "online",
    speed: "Fast",
    costLevel: "Low",
    icon: "Cpu",
    description: "Advanced deep reasoning model by Moonshot AI running on NVIDIA AI Endpoints. Supports full chain-of-thought extraction."
  },
  {
    id: "agent-nvidia-minimax",
    name: "Nvidia MiniMax Agent",
    provider: "NVIDIA AI Endpoints (minimax-m3)",
    role: "Multimodal & Adversarial Decision Expert",
    bestFor: "Game theory, minimax planning, strategic decision-making, and high-context multimodal reasoning",
    status: "online",
    speed: "Balanced",
    costLevel: "Low",
    icon: "BrainCircuit",
    description: "State-of-the-art decision-making and reasoning model by MiniMax running on NVIDIA AI Endpoints. Fully optimized for adversarial search algorithms."
  },
  {
    id: "agent-poolside",
    name: "Poolside Laguna Agent",
    provider: "Poolside Developer Model",
    role: "Advanced Developer Copilot",
    bestFor: "Large-scale refactoring, unit tests generation, typing corrections across extensive directories",
    status: "online",
    speed: "Ultra Fast",
    costLevel: "Medium",
    icon: "CodeXml",
    description: "Ultra-fast software development assistant built explicitly for full-stack programmers."
  },
  {
    id: "agent-inclusionai",
    name: "InclusionAI Ring Agent",
    provider: "InclusionAI Multi-Agent Ring",
    role: "Consensus Orchestrator",
    bestFor: "Comparing answers from multiple agents to construct perfectly accurate fact sheets",
    status: "online",
    speed: "Balanced",
    costLevel: "Medium",
    icon: "Layers",
    description: "Assembles multiple sub-models simultaneously and aligns their findings to build consolidated outputs."
  },
  {
    id: "agent-ibm-granite",
    name: "IBM Granite Agent",
    provider: "IBM Granite Core",
    role: "Enterprise Safety & Compliance Analyst",
    bestFor: "Auditing security parameters, legal phrasing, high compliance data tasks",
    status: "online",
    speed: "Fast",
    costLevel: "Low",
    icon: "Compass",
    description: "IBM's flagship open-weights model designed for reliable business logic and strict corporate rules."
  },
  {
    id: "agent-trend-predictor",
    name: "Trend & Career Predictor",
    provider: "Gemini 3.5 Core Engine",
    role: "Deep Career & Market Strategist",
    bestFor: "Predicting future demand, career roadmap, AI impacts, competitor voids, and content strategies",
    status: "online",
    speed: "Ultra Fast",
    costLevel: "Free",
    icon: "Compass",
    description: "Equipped with advanced trend predicting filters & strategic business templates. Can be accessed via the side navigation tab."
  }
];
